production:
  domain:
    name: "bricksco@bricksites.com"
    ssh_options: "-p 2222"
  deploy_to: "~/public_html/micahredding/postly"
  repository: "git@github.com:micahredding/postly.git"
  branch: "master"