production:
  domain:
  - name: "root@162.243.236.4"
  deploy_to: "/var/www/postly/"
  repository: "git@github.com:micahredding/postly.git"
  branch: "master"
  post_deploy_script: 'bin/post_deploy_script.sh'